version: "3"

networks:
  openvideo:

services:
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    networks:
      - openvideo
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./dev/neo4j/conf:/conf
      - ./dev/neo4j/logs:/logs
      - ./dev/neo4j/data:/data
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G

  openvideo-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: openvideo-server
    networks:
      - openvideo
    depends_on:
      - neo4j
    restart: unless-stopped
    env_file: ./dev/.env
    expose:
      - "4000"

  nginx:
    image: nginx:latest
    networks:
      - openvideo
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - openvideo-api
    ports:
      - "3000:3000"