MATCH (n) DETACH DELETE n;
CREATE CONSTRAINT ON (u:User) ASSERT u.name IS UNIQUE;
CREATE CONSTRAINT ON (l:Login) ASSERT l.id IS UNIQUE;
CREATE CONSTRAINT ON (s:Sound) ASSERT s.id IS UNIQUE;
CREATE CONSTRAINT ON (v:Video) ASSERT v.id IS UNIQUE;
CREATE CONSTRAINT ON (c:Comment) ASSERT c.id IS UNIQUE;